# Generated by Django 4.2.23 on 2025-08-09 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='max_capacity',
            field=models.PositiveIntegerField(default=50, help_text='Maximum reservations allowed for this slot', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
