# Generated by Django 4.2.23 on 2025-08-07 13:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='Actual time stored in 24h format (e.g. 17:30:00)', unique=True)),
                ('display_name', models.CharField(help_text="User-friendly name (e.g. '5:30 PM')", max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to disable slot temporarily')),
                ('max_capacity', models.PositiveIntegerField(default=10, help_text='Maximum reservations allowed for this slot', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Reservation date (YYYY-MM-DD)')),
                ('name', models.CharField(help_text='Customer name (fallback if not logged in)', max_length=100)),
                ('email', models.EmailField(help_text='Contact email for confirmation', max_length=254)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('guests', models.PositiveIntegerField(help_text='Number of attendees', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('special_requests', models.TextField(blank=True, help_text='Dietary needs or other requests', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When reservation was made')),
                ('is_cancelled', models.BooleanField(default=False, help_text='Soft delete toggle')),
                ('time_slot', models.ForeignKey(help_text='Selected booking time', on_delete=django.db.models.deletion.PROTECT, to='reservations.timeslot')),
                ('user', models.ForeignKey(help_text='User who made the reservation', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['date', 'time_slot__start_time'],
                'unique_together': {('date', 'time_slot', 'user')},
            },
        ),
    ]
